---
title: "ベイズ塾と私の2年間"
author: "Honami K"
date: 2020-12-01T10:13:14-05:00
categories: ["Personal"]
tags: ["personal"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

こんにちは、小林です。
認知心理学・実験心理学が専門で、主に視覚的注意の研究をしています。本好きです。好きなジャンルはSFとヴィクトリア朝文学です。今年、急に漢詩にはまり、最近になって和歌にも手を出しました。「[漢詩を読む](https://www.amazon.co.jp/%E6%BC%A2%E8%A9%A9%E3%82%92%E8%AA%AD%E3%82%80-1-%E3%80%8E%E8%A9%A9%E7%B5%8C%E3%80%8F%E3%80%81%E5%B1%88%E5%8E%9F%E3%81%8B%E3%82%89%E9%99%B6%E6%B7%B5%E6%98%8E%E3%81%B8-%E6%B1%9F%E5%8E%9F-%E6%AD%A3%E5%A3%AB/dp/4582834701)」シリーズがおすすめです。


これは[ベイズ塾アドベントカレンダー](https://adventar.org/calendars/5083)1日目の記事です。コロナ禍で交流の機会が少なくなったので、アドベントカレンダーを通して塾生の交友を深めようという趣旨のようです。

並行して[Stanアドベントカレンダー](https://qiita.com/advent-calendar/2020/stan)もあります。こちらでは12/1から10日間、Stan Advent Boot Campと称して10日でStanの基礎をおさらいする企画が進行中です。

Stanなど技術的なことはStanアドベントカレンダーに譲り、この記事では私の個人的な話を中心にしたいと思います。テーマは「ベイズ塾と私の2年間」です。モデリングのことを何も知らない状態でベイズ塾に入ってから2年間の、私の研究の歩みを紹介します。モデリングを始めてみようかなと思っている人・大学院への進学を考えている人などの参考になれば幸いです。


# 入塾のきっかけ（学部4年夏）

私がベイズ塾に入ったのは学部4年の秋、今からおおよそ2年前です。清水先生の社会心理学の講義を受けているときに「GLMMの勉強がしたいのですが」と言いに行ったところ、いろいろあってベイズ塾に入っていました。

そもそもなんで「GLMMの勉強がしたい」などと言い出したのかといえば、きっかけはある先生が「ANOVAの時代は終わった。これからはGLMMだ」とおっしゃったからでした。私はその先生を尊敬していたので（今もしています）、その先生がANOVAの時代が終わったというんだったらそうなんだろうと思ったのです。

GLMMの勉強をしに行ったはずなのにベイズ塾に入っていた経緯については省略しますが、とにかく私がベイズ塾に入ったきっかけはこんなものでした。当時は特にモデリングが何かの役に立つと思っていたわけでもなく、気づいたらモデリングせざるを得ない状況になっていました。


# 伸び悩み

ベイズ塾に入った学部4年の秋頃、私は卒論に追われていて、とても大変な時期でした。卒論の研究はあまりうまくいっていなかったので、自分より研究が進んでいる同期を見ては焦っていました。[^1]

[^1]: ただ、この同期には感謝しています。甘ったれていた学部時代の私が目を覚ますきっかけになってくれました。この同期を通してたくさんの素敵な先輩に出会うこともできました。

卒論を終えて大学院に進学してからも、うまくいかない時期が続いていました。卒論の内容を研究会や学会で発表する機会もありましたが、納得できる内容ではありませんでした。[^2][^3] 正直モデリングどころではありませんでした。このしんどい時期はM1の夏ごろまで続いたと思います。

[^2]: 小林穂波・小川洋和（2019/3/3)．自己に関する概念の変化が視覚的注意の焦点の範囲を調節する．日本心理学会「注意と認知」研究会 第17回合宿研究会．

[^3]: 小林穂波・小川洋和 (2019/5/26)．自己観の変化が視覚的注意のスポットライトの大きさを調節する．日本認知心理学会第17回大会，京都テルサ（京都府京都市）.


# 転機

しんどい時期を抜けるきっかけになったのは、Asia-Pacific Conference on Vision (APCV) の口頭発表です。[^4]

[^4]: Kobayashi, H., & Ogawa, H. (2019/7/31). Reading direction influences the deployment of visual attention during word processing. Paper presented at Asia-Pacific Conference on Vision 2019, Osaka, Japan.

これは大学3年のときに交換留学で訪れたレスター大学で単語処理研究に出会い、自分でもやってみたいと思って、卒論と並行して始めた研究です。M1の7月ごろにある程度形になってきたので、この学会で発表することになりました。これが私の国際学会デビューで、しかも口頭発表だったので、緊張して終わった後も胃痛がおさまらなかったのを覚えています。

このとき、ベイズ塾の先輩である[mutopsy](https://mutopsy.net/)さんが発表を見に来てくださっていました。発表後に「よい発表だった。今回の国際学会発表でめちゃくちゃ緊張したと思うので、今後の学会ではもう緊張しないだろう。この研究はたぶん何らかの形で論文にはなるだろう」という趣旨のことを言ってくださったのが、私の転機になりました。次の研究発表を楽しみにする気持ちを初めてこのとき持つことができました。それ以外にもお世話になりまくっているmutopsy先輩ですが、特にこれに関しては感謝しています。


# はじめてのモデリング研究

APCVに参加したころから、さっき登場したmutopsyさんと清水先生と、フランカー課題[^5]のモデリング研究を始めました。モデルの詳しい内容はいろいろな学会で話してきたのでそちらを参考にしてください。[^6] ベイズ統計モデリングをする上で重要なプログラミング言語Stanの技術・認知モデリングの基礎などは、この共同研究を通して勉強できました。

[^5]: 競合する情報からの反応干渉を調べる課題。視覚的注意の空間特性を調べるのにも用いられる

[^6]: Kobayashi, H., Muto, H., Shimizu, H., & Ogawa, H. (2019/11/14). A Bayesian hierarchical diffusion model of flanker interference. Paper presented at the Object Perception, Attention, & Memory (OPAM), Montreal, Canada.

統計モデリングをしたいと思ったときに、近くに相談できる先輩や先生がいるかどうかはとても大事だと思います。私は特に恵まれていて、同じ大学に清水先生がいたり、mutopsyさんともお話しする機会が多かったりと、わからないことがあったらすぐに相談できる環境でした。

ただ全員がこういう恵まれた環境にいるとは限りません。もし自分の大学に統計モデリングに詳しい人がいなくても気軽に詳しい人に相談できるので、ベイズ塾の存在は統計モデリングを普及するうえで非常に大きいと思います。


# モデリングは役に立つ

もう一つの転機は、M1の夏休みにおこなった文脈手がかり効果 (contextual cueing) の実験です。これまで心理物理関数を使って分析されてきた課題を使ったのですが、「[Bayesian Cognitive Modeling](https://bayesmodels.com/)」の本に心理物理関数を使った認知モデリングが載っていたので、自分でもやってみようと思いました。

この研究が非常にうまくいきました。12月の日本基礎心理学会大会で発表したところ[^7]、優秀発表賞をいただきました。さらに論文として投稿し、[Attention, Perception, & Psychophysics誌に掲載](https://doi.org/10.3758/s13414-020-02028-9)されました[^8]。

[^7]: 小林穂波・小川洋和 (2019/12/1)． 文脈手がかりは視覚探索処理の初期段階を促進する. 日本基礎心理学会第38回大会, 神戸大学（兵庫県神戸市）

[^8]: Kobayashi, H., & Ogawa, H. (2020). Contextual cueing facilitation arises early in the time course of visual search: An investigation with the speed-accuracy tradeoff task. *Attention, Perception, & Psychophysics*, *82*, 2851 - 2861.

11月に関西心理学会大会で発表した別の研究[^9]もこの頃に研究奨励賞をいただきました。これまでの研究生活で一番波に乗っていた時期ではないかと思います。この研究も論文として[Japanese Psychological Research誌に掲載](https://doi.org/10.1111/jpr.12315)されています[^10]。APCVのときの、mutopsyさんの「何らかの形で論文になる」という予言が的中したことになります。

[^9]: 小林穂波・小川洋和 (2019/11/10)．読み方向のプライミングが単語の並列処理を促進する．関西心理学会第131回大会，大阪教育大学 天王寺キャンパス（大阪府大阪市）

[^10]: Kobayashi, H., & Ogawa, H. (in press). Priming with horizontal reading influences the deployment of visual attention during word processing. Japanese Psychological Research. Advance online publication.

AP&P誌に論文が採択されたときに、「モデリング研究は評価される」ということを実感しました。もちろん実験計画や研究目的がダメだったらダメなのですが、そのあたりがうまくいっていればモデリング研究は素直に評価してもらえるな、と思いました。どちらかというと新しい方法なので論文や学会発表で評価されないのでは、と懸念している人がいるかもしれません。研究さえおもしろければモデリング研究は評価してもらえるので、安心してください。


# 現在とこれから

最近では、統計モデリングを使って視覚的注意の研究をする、のが自分のスタイルになりつつあります。ベイズ塾に入ってから2年でよくもここまで来たものだと思います。今後もこの路線は続けていくと思います。

私の経歴をざっくり書いてきましたが、何も知らない初心者でも2年ぐらいで実践に必要な力を身に付けられることが伝わっているでしょうか。これは統計モデリングに限らないと思います。何事も2年ぐらい真面目にやれば、ある程度の力はつくはずです。この2年、というのはちょうど修士課程の長さと一致しますので、統計モデリングを学部卒業と同時に勉強しはじめれば修士課程が終わるころには統計モデリングを使った研究ができるようになっているでしょう。

この2年間は、直接的・間接的にベイズ塾に助けられてきました。ベイズ塾の先輩たちがすごく楽しそうにモデリングや研究の話をするのを聞いて、何度も元気をもらいました。モデリング技術を身につけられたというのはもちろんですが、何が起こっても（たとえコロナが流行しても）この人たちは楽しく研究していくんだろう、と思える場所でもあり、しんどい時期を乗り越える助けになりました。

そもそもベイズ塾に入らなければ、今の私は絶対にいません。これまでベイズ塾を支えてこられた皆様に感謝するとともに、今後の繁栄を心から願います。

