---
title: "実験心理学者のためのJavaScript"
author: "Honami K"
date: 2020-04-29T21:13:14-05:00
categories: ["JavaScript"]
tags: ["exp"]
---

# 視覚探索課題を作りたい

昨今の情勢のおかげでweb実験の需要が高まっています。最近では[jsPsych](https://www.jspsych.org/)、[lab.js](https://lab.js.org/)など気軽に使えるツールが多くあり、単純な課題ならテンプレートが用意されているので、プログラミングをしなくてもすぐに実施することができます。lab.jsには[これだけ多くのテンプレート](https://github.com/FelixHenninger/lab.js/tree/master/tasks)が用意されています。すごいですね。

私は視覚探索課題のデータを主食にして生きているので、lab.jsに視覚探索課題が用意されているのを見て小躍りしたのですが、よく見てみたところ、私が普段使っている課題とは若干細部が異なっていることに気づきました。以下のようにアレンジしないと、普段通りの実験はできなさそうです。

(1) 画面上の刺激数 (セットサイズ) が複数条件用意されているのを、1条件のみにしたい
(2) 画面上の妨害刺激の回転角度を変えたい
(3) 「標的刺激の有無」を答える課題を、「標的刺激の向き」を答える課題にしたい
(4) 刺激の並びが整いすぎないように、適度に座標をずらして (ジター) 呈示したい
(5) 同じ刺激レイアウトを何度も使えるようにしたい

このうち(1)はlab.jsのBuilder機能を使えば簡単にできますが、それ以外はwebブラウザとかかわりの深いプログラミング言語であるJavaScriptを使ってスクリプトを書くことで解決できます。そこで、このチュートリアルでは、lab.jsにあらかじめ用意されている視覚探索課題をアレンジして(1)~(5)の要件を満たすような視覚探索課題を作ることを目標にします。


# チュートリアル: 実験心理学者のためのJavaScript
1. [JavaScript入門 (1)](https://www.notion.so/JavaScript-265e1c9350ad44cabcb6d62ba7cd5af2) (製作中)
2. [JavaScript入門 (2)](https://www.notion.so/JavaScript-2-38459ca3d20f4de394eadc9dc211fa16) (製作中)
3. [lab.jsの視覚探索課題をアレンジする (1)](https://www.notion.so/lab-js-1-919003c5d7e44dbdabddb6bcee74c111) (製作中)
4. [lab.jsの視覚探索課題をアレンジする (2)](https://www.notion.so/lab-js-1-c395eeb6f53744f8b51dbf50fd133f50) (製作中)


# 役に立ちそうなリンク集

- [lab.js](https://lab.js.org/)
- [lab.jsのドキュメント](https://labjs.readthedocs.io/en/latest/)

