---
title: "Stanを使ってモデリングするために：数学編"
author: "Honami K"
date: 2020-12-20
categories: ["Modeling"]
tags: ["stats", "Stan"]
---

[Stan Advent Calendar 2020](https://qiita.com/advent-calendar/2020/stan)20日目の記事です。ガウス過程を使った何かをやる、といっていましたが、今ちょっとそれどころではないです。代わりに、Stanを使ってモデリングができるようになるためには、どういう勉強が必要か？という話をします。今回は、数学編です。続くかは未定。

# 数学の勉強は必要ですよね

当然ですが。ときどき「数学が苦手でもできました！」という言葉を聞きますが、そんなわけあるか、といつも思っています。「英語しゃべれないけど国際学会で発表できました！」並みに無理があります。[^1]

[^1]: この場合、「自分ではしゃべれないと思っているけど実はしゃべれている」か「自分では発表できていると思っているけど実はあんまり理解されていない」か、のどっちかですよね。

モデルを数学的に表現するのが統計モデリングなのに、数学を知らなくてできるわけがありません（今ブーメランが自分にぶっ刺さっています）。モデリングしている人は、当然わかってやっているんですよね。数学使っているじゃないですか。まさか数式が何を言っているのかわからないままモデルを作っているわけじゃ、ないですよね？

数学ができない心理学者は引っ込んでろ！と言っているのではありません。そんなこと言ったら私の存在意義が消滅します。そうではなくて、「数学は苦手なのですが…」と枕詞を言っている暇があるなら勉強、じゃないでしょうか。[^2]

[^2]: 上に書いた英語発表の例も、きっと一緒です。

といっても、どのレベルの知識が求められるかは、難しいですよね。とりあえず今のところなんとかなっているレベルの知識は、これらの本で身につけました。


- [関数のはなし 上](https://www.amazon.co.jp/%E9%96%A2%E6%95%B0%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E3%80%88%E4%B8%8A%E3%80%89-%E5%A4%A7%E6%9D%91-%E5%B9%B3/dp/4817194405/ref=sr_1_1?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&dchild=1&keywords=%E9%96%A2%E6%95%B0%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97&qid=1608360082&s=books&sr=1-1)

- [関数のはなし 下](https://www.amazon.co.jp/%E9%96%A2%E6%95%B0%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E3%80%88%E4%B8%8B%E3%80%89-%E5%A4%A7%E6%9D%91-%E5%B9%B3/dp/4817194413/ref=pd_bxgy_img_2/355-3598662-4428548?_encoding=UTF8&pd_rd_i=4817194413&pd_rd_r=8930634e-abab-46ee-ad11-825fb17d236e&pd_rd_w=AOH3J&pd_rd_wg=PI0xX&pf_rd_p=e64b0a81-ca1b-4802-bd2c-a4b65bccc76e&pf_rd_r=MW00ZE0S9SP7RG7GSWY6&psc=1&refRID=MW00ZE0S9SP7RG7GSWY6)

- [行列とベクトルのはなし](https://www.amazon.co.jp/%E8%A1%8C%E5%88%97%E3%81%A8%E3%83%99%E3%82%AF%E3%83%88%E3%83%AB%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E2%80%95%E7%B7%9A%E5%BD%A2%E4%BB%A3%E6%95%B0%E3%81%AE%E5%9F%BA%E7%A4%8E-%E5%A4%A7%E6%9D%91-%E5%B9%B3/dp/4817195436)

- [微積分のはなし 上](https://www.amazon.co.jp/%E5%BE%AE%E7%A9%8D%E5%88%86%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E3%80%88%E4%B8%8A%E3%80%89%E5%A4%89%E5%8C%96%E3%81%A8%E7%B5%90%E6%9E%9C%E3%82%92%E7%9F%A5%E3%82%8B%E3%83%86%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF-%E5%A4%A7%E6%9D%91-%E5%B9%B3/dp/4817192437/ref=pd_bxgy_img_2/355-3598662-4428548?_encoding=UTF8&pd_rd_i=4817192437&pd_rd_r=fb5a4456-35b9-4b53-834f-9c36edc18d35&pd_rd_w=eKBM1&pd_rd_wg=73Hne&pf_rd_p=e64b0a81-ca1b-4802-bd2c-a4b65bccc76e&pf_rd_r=R499C3TA3EA3FKGP174E&psc=1&refRID=R499C3TA3EA3FKGP174E)

- [微積分のはなし 下](https://www.amazon.co.jp/%E5%BE%AE%E7%A9%8D%E5%88%86%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%97%E2%80%95%E5%A4%89%E5%8C%96%E3%81%A8%E7%B5%90%E6%9E%9C%E3%82%92%E7%9F%A5%E3%82%8B%E3%83%86%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF%E3%80%88%E4%B8%8B%E3%80%89-%E5%A4%A7%E6%9D%91-%E5%B9%B3/dp/4817192445/ref=pd_bxgy_img_2/355-3598662-4428548?_encoding=UTF8&pd_rd_i=4817192445&pd_rd_r=37a00983-2358-4169-a8da-7981ed6730e7&pd_rd_w=kIRgI&pd_rd_wg=DuNab&pf_rd_p=e64b0a81-ca1b-4802-bd2c-a4b65bccc76e&pf_rd_r=1N1K3WRME6X7JZ2EGXCX&psc=1&refRID=1N1K3WRME6X7JZ2EGXCX)


「はなし」シリーズ、最強です。おすすめ。もともと「微積分のはなし」を、数学が得意な某先輩に教えてもらいました。めちゃめちゃ感謝しています。「読んで数式を一通り追ったらできるよ！」といわれて、ほんまかいな、と半信半疑だったのですが、ほんまでした。先輩すごい。調子に乗って線形代数のも読みました。一応、一通りの行列演算は（ちゃんと思い出せば）できます。

モデリングユーザーとしては、これぐらいで、モデルが何を言っているか、とか、[社会科学のためのベイズ統計モデリング](http://www.asakura.co.jp/books/isbn/978-4-254-12842-0/)の数式（ただしすごく丁寧に解説されている）は理解できます。

あと、edXにあるハーバードの確率についての講義は聞いてよかったなと思います。

- [Introduction to Probability](https://www.edx.org/course/introduction-to-probability)

最後のユニットはちょっと難しくてついていけなくなってしまったのですが、確率変数とか確率分布とか、確率の基本的な概念が整理できてよかったです。時間ができたら再受講したいと思います。ちなみに本もあります。ここの[コースページ](https://projects.iq.harvard.edu/stat110/home)で公開されています。おすすめ。

最近は、基礎を固めるためにこれをやっています。

- [もう一度高校数学](https://www.amazon.co.jp/%E3%82%82%E3%81%86%E4%B8%80%E5%BA%A6%E9%AB%98%E6%A0%A1%E6%95%B0%E5%AD%A6-%E9%AB%98%E6%A9%8B-%E4%B8%80%E9%9B%84/dp/4534045840)

忙しすぎて全然進んでいないですが。でも忘れかけていることとか、思い出せて助かっています。この本も、もともとモデリングが得意な某先輩 (さっき出てきた先輩とは別の人です) に教えてもらいました。ありがとうございます！他にもいっぱい本を教えてもらったので、勉強がんばります。


こんなところですかね。ガウス過程じゃなくてすみません。モデリングをやってみたい人の参考になれば幸いです。ガウス過程は、必ず、いつか書きます。
