---
title: "About"
description: ""
draft: true
---

過去の経験・学習・記憶が認知処理を促進するメカニズムに興味があります。

認知モデリングを使った情報処理過程の解明にも取り組んでいます。

# 主な研究テーマ

- 時空間的統計情報の学習・利用メカニズムの解明
    - 文脈手がかり効果による注意処理促進メカニズム
    - 時間次元における確率情報の学習・利用メカニズム
    - 統計学習によって形成される記憶表象についての検討
- 統計モデリングを用いた視覚的注意の空間特性の解明
- 単語の並列処理に視覚的注意が及ぼす影響についての検討


# 業績・発表予定

## 論文

- Kobayashi, H., & Ogawa, H. (in press). [Priming with horizontal reading influences the deployment of visual attention during word processing](https://doi.org/10.1111/jpr.12315). *Japanese Psychological Research*.

- Kobayashi, H., & Ogawa, H. (2020). [Contextual cueing facilitation arises early in the time course of visual search: An investigation with the speed-accuracy tradeoff task.](https://link.springer.com/article/10.3758/s13414-020-02028-9) *Attention, Perception, & Psychophysics*, *82*, 2851 - 2861.


## 発表予定

- Kobayashi, H., Muto, H., Shimizu, H., & Ogawa, H. (2021). Effects of interstimulus spacing on flanker interference investigated by hierarchical diffusion modeling. The 18th Annual Convention of the Japanese Society for Cognitive Psychology, Kanazawa Institute of Technology, March 3-4.


## 学会発表

- 小林 穂波・小川 洋和 (2020). Investigating visual attention with statistical modeling: The time course of contextual cueing effect 　日本基礎心理学会第39回大会　オンライン若手セッション, 北海道大学 (web開催), 11月7日-11月17日.

- 小林 穂波 (2020). 文脈手がかりは視覚探索の初期段階を促進する──SAT課題と統計モデリングを用いた検討── 　公募シンポジウム「心理学の諸領域におけるベイズ統計モデリングの実践」, 東洋大学（Web開催）, 9月8日-11月2日.（企画：武藤 拓之，難波 修史，司会：武藤 拓之，話題提供：小林 穂波，難波 修史，水野 景子，横山 仁史，松井 大，指定討論：小杉 考司）

- Kobayashi, H., & Ogawa, H. (2020/06/19). An early locus of contextual cueing: An investigation with the speed-accuracy tradeoff task. Paper presented at Vision Sciences Society (virtual meeting).

- 小林穂波・小川洋和 (2019/12/1)． 文脈手がかりは視覚探索処理の初期段階を促進する. 日本基礎心理学会第38回大会, 神戸大学（兵庫県神戸市）

- 小林穂波・小川洋和 (2019/11/10)．読み方向のプライミングが単語の並列処理を促進する．関西心理学会第131回大会，大阪教育大学 天王寺キャンパス（大阪府大阪市）

- Kobayashi, H., Muto, H., Shimizu, H., & Ogawa, H. (2019/11/14). A Bayesian hierarchical diffusion model of flanker interference. Paper presented at the Object Perception, Attention, & Memory (OPAM), Montreal, Canada.

- Kobayashi, H., & Ogawa, H. (2019/7/31). Reading direction influences the deployment of visual attention during word processing. Paper presented at Asia-Pacific Conference on Vision 2019, Osaka, Japan.

- 小林穂波・小川洋和 (2019/5/26)．自己観の変化が視覚的注意のスポットライトの大きさを調節する．日本認知心理学会第17回大会，京都テルサ（京都府京都市）. 


## 研究会発表

- 小林穂波・小川洋和（2019/3/3)．自己に関する概念の変化が視覚的注意の焦点の範囲を調節する．日本心理学会「注意と認知」研究会 第17回合宿研究会．



## 受賞

- 日本基礎心理学会第38回大会　優秀発表賞 (発表タイトル: 文脈手がかりは視覚探索処理の初期段階を促進する)

- 関西心理学会第131回大会　関西心理学会研究奨励賞 (発表タイトル: 読み方向のプライミングが単語の並列処理を促進する)
